import React from 'react';
import { Badge } from '@/components/ui/badge';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { 
  CheckCircle2, 
  AlertCircle, 
  XCircle, 
  Bot, 
  FileEdit, 
  Eye, 
  ThumbsUp,
  HelpCircle
} from 'lucide-react';

export type TranslationIndicatorStatus = 
  | 'no_key' 
  | 'no_translation' 
  | 'ai_generated' 
  | 'draft' 
  | 'reviewed' 
  | 'approved'
  | 'partial';

interface TranslationStatusIndicatorProps {
  status: TranslationIndicatorStatus;
  size?: 'xs' | 'sm' | 'default';
  showLabel?: boolean;
  showTooltip?: boolean;
  translatedCount?: number;
  totalCount?: number;
}

const statusConfig: Record<TranslationIndicatorStatus, {
  icon: React.ElementType;
  label: string;
  shortLabel: string;
  description: string;
  colorClass: string;
  bgClass: string;
  borderClass: string;
}> = {
  no_key: {
    icon: XCircle,
    label: 'No Key',
    shortLabel: '—',
    description: 'This element has no translation key assigned. Click to add one.',
    colorClass: 'text-red-500',
    bgClass: 'bg-red-50 dark:bg-red-900/20',
    borderClass: 'border-red-200 dark:border-red-800'
  },
  no_translation: {
    icon: AlertCircle,
    label: 'Not Translated',
    shortLabel: '—',
    description: 'Has a key but no translation for this language yet.',
    colorClass: 'text-gray-400',
    bgClass: 'bg-gray-50 dark:bg-gray-900/20',
    borderClass: 'border-gray-200 dark:border-gray-700'
  },
  ai_generated: {
    icon: Bot,
    label: 'AI Generated',
    shortLabel: 'AI',
    description: 'This translation was auto-generated by AI. Review before publishing.',
    colorClass: 'text-blue-500',
    bgClass: 'bg-blue-50 dark:bg-blue-900/20',
    borderClass: 'border-blue-200 dark:border-blue-800'
  },
  draft: {
    icon: FileEdit,
    label: 'Draft',
    shortLabel: 'Draft',
    description: 'Translation saved but pending review.',
    colorClass: 'text-yellow-600',
    bgClass: 'bg-yellow-50 dark:bg-yellow-900/20',
    borderClass: 'border-yellow-200 dark:border-yellow-800'
  },
  reviewed: {
    icon: Eye,
    label: 'Reviewed',
    shortLabel: 'Reviewed',
    description: 'Translation has been reviewed but not yet approved.',
    colorClass: 'text-purple-500',
    bgClass: 'bg-purple-50 dark:bg-purple-900/20',
    borderClass: 'border-purple-200 dark:border-purple-800'
  },
  approved: {
    icon: CheckCircle2,
    label: 'Approved',
    shortLabel: '✓',
    description: 'Translation approved and ready for production.',
    colorClass: 'text-green-500',
    bgClass: 'bg-green-50 dark:bg-green-900/20',
    borderClass: 'border-green-200 dark:border-green-800'
  },
  partial: {
    icon: HelpCircle,
    label: 'Partial',
    shortLabel: 'Partial',
    description: 'Some languages are translated, others are missing.',
    colorClass: 'text-orange-500',
    bgClass: 'bg-orange-50 dark:bg-orange-900/20',
    borderClass: 'border-orange-200 dark:border-orange-800'
  }
};

export const TranslationStatusIndicator: React.FC<TranslationStatusIndicatorProps> = ({
  status,
  size = 'default',
  showLabel = true,
  showTooltip = true,
  translatedCount,
  totalCount
}) => {
  const config = statusConfig[status];
  const Icon = config.icon;
  
  const sizeClasses = {
    xs: 'h-3 w-3',
    sm: 'h-3.5 w-3.5',
    default: 'h-4 w-4'
  };
  
  const badgeSizeClasses = {
    xs: 'text-[9px] px-1 py-0 h-4',
    sm: 'text-[10px] px-1.5 py-0 h-5',
    default: 'text-xs px-2 py-0.5'
  };
  
  const indicator = (
    <Badge 
      variant="outline" 
      className={`${config.bgClass} ${config.borderClass} ${badgeSizeClasses[size]} gap-1`}
    >
      <Icon className={`${sizeClasses[size]} ${config.colorClass}`} />
      {showLabel && (
        <span className={config.colorClass}>
          {translatedCount !== undefined && totalCount !== undefined 
            ? `${translatedCount}/${totalCount}` 
            : config.shortLabel
          }
        </span>
      )}
    </Badge>
  );
  
  if (!showTooltip) return indicator;
  
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          {indicator}
        </TooltipTrigger>
        <TooltipContent side="top" className="max-w-xs">
          <p className="font-medium">{config.label}</p>
          <p className="text-xs text-muted-foreground">{config.description}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};

// Human-readable key formatter
export const formatTranslationKey = (key: string): string => {
  // Convert section.tag.descriptor_content to Section → Tag → Description
  const parts = key.split('.');
  if (parts.length < 2) return key;
  
  const formatPart = (part: string): string => {
    return part
      .replace(/_/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase())
      .trim();
  };
  
  // Section
  const section = formatPart(parts[0]);
  
  // Tag (if exists)
  const tag = parts[1] ? `<${parts[1]}>` : '';
  
  // Rest joined as description
  const description = parts.slice(2).map(formatPart).join(' ');
  
  const formatted = [section, tag, description].filter(Boolean);
  return formatted.join(' → ');
};

// Get appropriate status from translation data
export const getTranslationStatus = (
  hasKey: boolean,
  translationValue?: string,
  isAiGenerated?: boolean,
  dbStatus?: string
): TranslationIndicatorStatus => {
  if (!hasKey) return 'no_key';
  if (!translationValue) return 'no_translation';
  if (isAiGenerated) return 'ai_generated';
  if (dbStatus === 'approved') return 'approved';
  if (dbStatus === 'reviewed') return 'reviewed';
  return 'draft';
};

export default TranslationStatusIndicator;
