-- Translate all homepage keys to proper translations for each language

-- Spanish translations
UPDATE public.translations SET value = 'Pregunta cualquier cosa' WHERE namespace = 'homepage' AND key = 'ask_anything' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Basado en más de 2,000 reseñas' WHERE namespace = 'homepage' AND key = 'based_on_reviews' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Asesor de dominios inteligente' WHERE namespace = 'homepage' AND key = 'domain_advisor' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Ancho de banda ilimitado' WHERE namespace = 'homepage' AND key = 'feature_bandwidth' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Protección DDoS gratuita' WHERE namespace = 'homepage' AND key = 'feature_ddos' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Soporte 24/7' WHERE namespace = 'homepage' AND key = 'feature_support' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '99.9% de tiempo activo' WHERE namespace = 'homepage' AND key = 'feature_uptime' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '⚡ Oferta flash: 75% de descuento en hosting web - ¡Termina hoy!' WHERE namespace = 'homepage' AND key = 'flash_sale_text' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Experto amigable en hosting' WHERE namespace = 'homepage' AND key = 'friendly_expert_alt' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Comenzar ahora' WHERE namespace = 'homepage' AND key = 'get_started_now' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Hosting web confiable' WHERE namespace = 'homepage' AND key = 'hero_title_line1' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'desde $3.29/mes' WHERE namespace = 'homepage' AND key = 'hero_title_line2' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Presentamos UltraAI' WHERE namespace = 'homepage' AND key = 'introducing_ultra_ai' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'La gente dice que es excelente' WHERE namespace = 'homepage' AND key = 'people_say_excellent' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '/mes' WHERE namespace = 'homepage' AND key = 'per_month' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '$7.99/mes' WHERE namespace = 'homepage' AND key = 'price_bluehost' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '$4.95/mes' WHERE namespace = 'homepage' AND key = 'price_dreamhost' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '$6.95/mes' WHERE namespace = 'homepage' AND key = 'price_hostgator' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '$8.99/mes' WHERE namespace = 'homepage' AND key = 'price_siteground' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '$3.29/mes' WHERE namespace = 'homepage' AND key = 'price_ultrahost' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Puntuación 4.8' WHERE namespace = 'homepage' AND key = 'rated_score' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '1,000+ reseñas' WHERE namespace = 'homepage' AND key = 'reviews_count_1000' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '1,704 reseñas' WHERE namespace = 'homepage' AND key = 'reviews_count_1704' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = '300+ reseñas' WHERE namespace = 'homepage' AND key = 'reviews_count_300' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Garantía sin riesgo de 30 días' WHERE namespace = 'homepage' AND key = 'risk_free_guarantee' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Ahorra 75%' WHERE namespace = 'homepage' AND key = 'save_percent' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Comenzando en' WHERE namespace = 'homepage' AND key = 'starting_at' AND language_id = (SELECT id FROM languages WHERE code = 'es');
UPDATE public.translations SET value = 'Prueba UltraAI' WHERE namespace = 'homepage' AND key = 'try_ultra_ai' AND language_id = (SELECT id FROM languages WHERE code = 'es');

-- French translations
UPDATE public.translations SET value = 'Demandez n''importe quoi' WHERE namespace = 'homepage' AND key = 'ask_anything' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Basé sur plus de 2 000 avis' WHERE namespace = 'homepage' AND key = 'based_on_reviews' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Conseiller de domaine intelligent' WHERE namespace = 'homepage' AND key = 'domain_advisor' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Bande passante illimitée' WHERE namespace = 'homepage' AND key = 'feature_bandwidth' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Protection DDoS gratuite' WHERE namespace = 'homepage' AND key = 'feature_ddos' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Support 24/7' WHERE namespace = 'homepage' AND key = 'feature_support' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '99,9% de disponibilité' WHERE namespace = 'homepage' AND key = 'feature_uptime' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '⚡ Offre flash : 75% de réduction sur l''hébergement web - Se termine aujourd''hui !' WHERE namespace = 'homepage' AND key = 'flash_sale_text' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Expert en hébergement sympathique' WHERE namespace = 'homepage' AND key = 'friendly_expert_alt' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Commencer maintenant' WHERE namespace = 'homepage' AND key = 'get_started_now' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Hébergement web fiable' WHERE namespace = 'homepage' AND key = 'hero_title_line1' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'à partir de 3,29€/mois' WHERE namespace = 'homepage' AND key = 'hero_title_line2' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Présentation d''UltraAI' WHERE namespace = 'homepage' AND key = 'introducing_ultra_ai' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Les gens disent que c''est excellent' WHERE namespace = 'homepage' AND key = 'people_say_excellent' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '/mois' WHERE namespace = 'homepage' AND key = 'per_month' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '7,99€/mois' WHERE namespace = 'homepage' AND key = 'price_bluehost' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '4,95€/mois' WHERE namespace = 'homepage' AND key = 'price_dreamhost' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '6,95€/mois' WHERE namespace = 'homepage' AND key = 'price_hostgator' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '8,99€/mois' WHERE namespace = 'homepage' AND key = 'price_siteground' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '3,29€/mois' WHERE namespace = 'homepage' AND key = 'price_ultrahost' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Note 4,8' WHERE namespace = 'homepage' AND key = 'rated_score' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '1 000+ avis' WHERE namespace = 'homepage' AND key = 'reviews_count_1000' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '1 704 avis' WHERE namespace = 'homepage' AND key = 'reviews_count_1704' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = '300+ avis' WHERE namespace = 'homepage' AND key = 'reviews_count_300' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Garantie sans risque de 30 jours' WHERE namespace = 'homepage' AND key = 'risk_free_guarantee' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Économisez 75%' WHERE namespace = 'homepage' AND key = 'save_percent' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'À partir de' WHERE namespace = 'homepage' AND key = 'starting_at' AND language_id = (SELECT id FROM languages WHERE code = 'fr');
UPDATE public.translations SET value = 'Essayer UltraAI' WHERE namespace = 'homepage' AND key = 'try_ultra_ai' AND language_id = (SELECT id FROM languages WHERE code = 'fr');

-- German translations
UPDATE public.translations SET value = 'Fragen Sie alles' WHERE namespace = 'homepage' AND key = 'ask_anything' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Basierend auf über 2.000 Bewertungen' WHERE namespace = 'homepage' AND key = 'based_on_reviews' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Intelligenter Domain-Berater' WHERE namespace = 'homepage' AND key = 'domain_advisor' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Unbegrenzte Bandbreite' WHERE namespace = 'homepage' AND key = 'feature_bandwidth' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Kostenloser DDoS-Schutz' WHERE namespace = 'homepage' AND key = 'feature_ddos' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '24/7 Support' WHERE namespace = 'homepage' AND key = 'feature_support' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '99,9% Verfügbarkeit' WHERE namespace = 'homepage' AND key = 'feature_uptime' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '⚡ Flash-Angebot: 75% Rabatt auf Webhosting - Endet heute!' WHERE namespace = 'homepage' AND key = 'flash_sale_text' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Freundlicher Hosting-Experte' WHERE namespace = 'homepage' AND key = 'friendly_expert_alt' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Jetzt starten' WHERE namespace = 'homepage' AND key = 'get_started_now' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Zuverlässiges Webhosting' WHERE namespace = 'homepage' AND key = 'hero_title_line1' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'ab 3,29€/Monat' WHERE namespace = 'homepage' AND key = 'hero_title_line2' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Wir stellen UltraAI vor' WHERE namespace = 'homepage' AND key = 'introducing_ultra_ai' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Die Leute sagen, es ist ausgezeichnet' WHERE namespace = 'homepage' AND key = 'people_say_excellent' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '/Monat' WHERE namespace = 'homepage' AND key = 'per_month' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '7,99€/Monat' WHERE namespace = 'homepage' AND key = 'price_bluehost' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '4,95€/Monat' WHERE namespace = 'homepage' AND key = 'price_dreamhost' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '6,95€/Monat' WHERE namespace = 'homepage' AND key = 'price_hostgator' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '8,99€/Monat' WHERE namespace = 'homepage' AND key = 'price_siteground' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '3,29€/Monat' WHERE namespace = 'homepage' AND key = 'price_ultrahost' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Bewertung 4,8' WHERE namespace = 'homepage' AND key = 'rated_score' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '1.000+ Bewertungen' WHERE namespace = 'homepage' AND key = 'reviews_count_1000' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '1.704 Bewertungen' WHERE namespace = 'homepage' AND key = 'reviews_count_1704' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '300+ Bewertungen' WHERE namespace = 'homepage' AND key = 'reviews_count_300' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = '30-Tage risikofreie Garantie' WHERE namespace = 'homepage' AND key = 'risk_free_guarantee' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Sparen Sie 75%' WHERE namespace = 'homepage' AND key = 'save_percent' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'Ab' WHERE namespace = 'homepage' AND key = 'starting_at' AND language_id = (SELECT id FROM languages WHERE code = 'de');
UPDATE public.translations SET value = 'UltraAI testen' WHERE namespace = 'homepage' AND key = 'try_ultra_ai' AND language_id = (SELECT id FROM languages WHERE code = 'de');

-- Arabic translations  
UPDATE public.translations SET value = 'اسأل أي شيء' WHERE namespace = 'homepage' AND key = 'ask_anything' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'بناءً على أكثر من 2000 مراجعة' WHERE namespace = 'homepage' AND key = 'based_on_reviews' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'مستشار النطاقات الذكي' WHERE namespace = 'homepage' AND key = 'domain_advisor' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'عرض نطاق غير محدود' WHERE namespace = 'homepage' AND key = 'feature_bandwidth' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'حماية DDoS مجانية' WHERE namespace = 'homepage' AND key = 'feature_ddos' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'دعم 24/7' WHERE namespace = 'homepage' AND key = 'feature_support' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '99.9% وقت تشغيل' WHERE namespace = 'homepage' AND key = 'feature_uptime' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '⚡ عرض فلاش: خصم 75% على استضافة المواقع - ينتهي اليوم!' WHERE namespace = 'homepage' AND key = 'flash_sale_text' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'خبير استضافة ودود' WHERE namespace = 'homepage' AND key = 'friendly_expert_alt' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'ابدأ الآن' WHERE namespace = 'homepage' AND key = 'get_started_now' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'استضافة مواقع موثوقة' WHERE namespace = 'homepage' AND key = 'hero_title_line1' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'ابتداءً من $3.29/شهر' WHERE namespace = 'homepage' AND key = 'hero_title_line2' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'نقدم UltraAI' WHERE namespace = 'homepage' AND key = 'introducing_ultra_ai' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'الناس يقولون أنه ممتاز' WHERE namespace = 'homepage' AND key = 'people_say_excellent' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '/شهر' WHERE namespace = 'homepage' AND key = 'per_month' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '$7.99/شهر' WHERE namespace = 'homepage' AND key = 'price_bluehost' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '$4.95/شهر' WHERE namespace = 'homepage' AND key = 'price_dreamhost' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '$6.95/شهر' WHERE namespace = 'homepage' AND key = 'price_hostgator' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '$8.99/شهر' WHERE namespace = 'homepage' AND key = 'price_siteground' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '$3.29/شهر' WHERE namespace = 'homepage' AND key = 'price_ultrahost' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'تقييم 4.8' WHERE namespace = 'homepage' AND key = 'rated_score' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '1000+ مراجعة' WHERE namespace = 'homepage' AND key = 'reviews_count_1000' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '1704 مراجعة' WHERE namespace = 'homepage' AND key = 'reviews_count_1704' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = '300+ مراجعة' WHERE namespace = 'homepage' AND key = 'reviews_count_300' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'ضمان 30 يوم بدون مخاطر' WHERE namespace = 'homepage' AND key = 'risk_free_guarantee' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'وفر 75%' WHERE namespace = 'homepage' AND key = 'save_percent' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'ابتداءً من' WHERE namespace = 'homepage' AND key = 'starting_at' AND language_id = (SELECT id FROM languages WHERE code = 'ar');
UPDATE public.translations SET value = 'جرب UltraAI' WHERE namespace = 'homepage' AND key = 'try_ultra_ai' AND language_id = (SELECT id FROM languages WHERE code = 'ar');